spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/TodoListServer
    username: root
    password: Aim123123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true